# Generated by Django 5.1.1 on 2024-10-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('NF', 'NAO_FICCAO'), ('F', 'FICCAO')], default='F', max_length=2)),
            ],
        ),
    ]
